# Generated by Django 2.2.17 on 2020-12-06 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorial', '0002_auto_20201206_0542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tutorial',
        ),
    ]
