# Generated by Django 3.1.4 on 2020-12-13 05:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20201206_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
