# Generated by Django 3.1.4 on 2020-12-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_tutorial_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='thumbnail',
            field=models.ImageField(default='uploads/my-avatar.png', upload_to='uploads/'),
        ),
    ]
